// <auto-generated />
using System;
using MapApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MapApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("MapApp.Models.Pin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrls")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Lat")
                        .HasColumnType("REAL");

                    b.Property<double>("Lng")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Pins");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7890-1234-567890abcdef"),
                            Description = "Karachi Port - A major seaport in Pakistan.",
                            ImageUrls = "[\"/images/default_port.jpg\"]",
                            Lat = 24.860700000000001,
                            Lng = 67.001099999999994
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-f6a7-8901-2345-67890abcdef0"),
                            Description = "Frere Hall - Historic building in Karachi.",
                            ImageUrls = "[\"/images/default_frerehall.jpg\"]",
                            Lat = 24.8567,
                            Lng = 67.029700000000005
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-a7b8-9012-3456-7890abcdef12"),
                            Description = "Clifton Beach - Popular recreational spot.",
                            ImageUrls = "[\"/images/default_cliftonbeach.jpg\"]",
                            Lat = 24.779599999999999,
                            Lng = 67.027799999999999
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
